SET SERVEROUTPUT ON;
declare 
v_cnt number;
begin
    select count(*) into v_cnt from user_tables where table_name = upper('customer');
    if v_cnt = 0 then
        execute immediate('
            create table customer (
            customer_id number PRIMARY KEY,
            first_name varchar(50),
            last_name varchar(50),
            date_of_birth DATE,
            phone_number number(10),
            email varchar(50),
            status varchar(1),
            pass_hash varchar(50),
            update_timestamp timestamp default systimestamp)');
        dbms_output.put_line('Customer table created');
        
    else
        dbms_output.put_line('Customer table already exists');
    end if;
end;
/

grant select on customer to item_owner;


SET DEFINE OFF

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (1, 'James', 'Butt', to_date('01/01/1965', 'MM/DD/RRRR'), 5046218927, 'jbutt@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (2, 'Josephine', 'Darakjy', to_date('04/28/1983', 'MM/DD/RRRR'), 8102929388, 'josephine_darakjy@darakjy.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (3, 'Art', 'Venere', to_date('01/27/1998', 'MM/DD/RRRR'), 8566368749, 'art@venere.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (4, 'Lenna', 'Paprocki', to_date('05/24/2000', 'MM/DD/RRRR'), 9073854412, 'lpaprocki@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (5, 'Donette', 'Foller', to_date('01/21/1987', 'MM/DD/RRRR'), 5135701893, 'donette.foller@cox.net', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (6, 'Simona', 'Morasca', to_date('01/28/1989', 'MM/DD/RRRR'), 4195032484, 'simona@morasca.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (7, 'Mitsue', 'Tollner', to_date('03/24/1992', 'MM/DD/RRRR'), 7735736914, 'mitsue_tollner@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (8, 'Leota', 'Dilliard', to_date('11/24/1979', 'MM/DD/RRRR'), 4087523500, 'leota@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (9, 'Sage', 'Wieser', to_date('10/26/1965', 'MM/DD/RRRR'), 6054142147, 'sage_wieser@cox.net', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (10, 'Kris', 'Marrier', to_date('05/13/1965', 'MM/DD/RRRR'), 4106558723, 'kris@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (11, 'Minna', 'Amigon', to_date('12/16/1980', 'MM/DD/RRRR'), 2158741229, 'minna_amigon@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (12, 'Abel', 'Maclead', to_date('03/28/1998', 'MM/DD/RRRR'), 6313353414, 'amaclead@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (13, 'Kiley', 'Caldarera', to_date('07/27/1992', 'MM/DD/RRRR'), 3104985651, 'kiley.caldarera@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (14, 'Graciela', 'Ruta', to_date('04/05/1985', 'MM/DD/RRRR'), 4407808425, 'gruta@cox.net', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (15, 'Cammy', 'Albares', to_date('08/05/1967', 'MM/DD/RRRR'), 9565376195, 'calbares@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (16, 'Mattie', 'Poquette', to_date('03/07/1993', 'MM/DD/RRRR'), 6022774385, 'mattie@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (17, 'Meaghan', 'Garufi', to_date('01/04/1969', 'MM/DD/RRRR'), 9313139635, 'meaghan@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (18, 'Gladys', 'Rim', to_date('07/20/1992', 'MM/DD/RRRR'), 4146619598, 'gladys.rim@rim.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (19, 'Yuki', 'Whobrey', to_date('01/30/1983', 'MM/DD/RRRR'), 3132887937, 'yuki_whobrey@aol.com', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (20, 'Fletcher', 'Flosi', to_date('11/15/1988', 'MM/DD/RRRR'), 8158282147, 'fletcher.flosi@yahoo.com', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (21, 'Bette', 'Nicka', to_date('02/04/1981', 'MM/DD/RRRR'), 6105453615, 'bette_nicka@cox.net', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (22, 'Veronika', 'Inouye', to_date('07/16/1980', 'MM/DD/RRRR'), 4085401785, 'vinouye@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (23, 'Willard', 'Kolmetz', to_date('10/20/1986', 'MM/DD/RRRR'), 9723039197, 'willard@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (24, 'Maryann', 'Royster', to_date('07/07/1982', 'MM/DD/RRRR'), 5189667987, 'mroyster@royster.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (25, 'Alisha', 'Slusarski', to_date('10/25/1973', 'MM/DD/RRRR'), 7326583154, 'alisha@slusarski.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (26, 'Allene', 'Iturbide', to_date('12/24/1976', 'MM/DD/RRRR'), 7156626764, 'allene_iturbide@cox.net', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (27, 'Chanel', 'Caudy', to_date('01/12/1993', 'MM/DD/RRRR'), 9133882079, 'chanel.caudy@caudy.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (28, 'Ezekiel', 'Chui', to_date('09/15/1998', 'MM/DD/RRRR'), 4106691642, 'ezekiel@chui.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (29, 'Willow', 'Kusko', to_date('05/12/1969', 'MM/DD/RRRR'), 2125824976, 'wkusko@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (30, 'Bernardo', 'Figeroa', to_date('03/11/1997', 'MM/DD/RRRR'), 9363363951, 'bfigeroa@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (31, 'Ammie', 'Corrio', to_date('06/07/1965', 'MM/DD/RRRR'), 6148019788, 'ammie@corrio.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (32, 'Francine', 'Vocelka', to_date('03/31/1994', 'MM/DD/RRRR'), 5059773911, 'francine_vocelka@vocelka.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (33, 'Ernie', 'Stenseth', to_date('07/22/1992', 'MM/DD/RRRR'), 2017096245, 'ernie_stenseth@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (34, 'Albina', 'Glick', to_date('12/15/1996', 'MM/DD/RRRR'), 7329247882, 'albina@glick.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (35, 'Alishia', 'Sergi', to_date('06/19/1988', 'MM/DD/RRRR'), 2128601579, 'asergi@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (36, 'Solange', 'Shinko', to_date('04/08/1965', 'MM/DD/RRRR'), 5049799175, 'solange@shinko.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (37, 'Jose', 'Stockham', to_date('06/14/1969', 'MM/DD/RRRR'), 2126758570, 'jose@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (38, 'Rozella', 'Ostrosky', to_date('08/16/1979', 'MM/DD/RRRR'), 8058326163, 'rozella.ostrosky@ostrosky.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (39, 'Valentine', 'Gillian', to_date('03/27/1996', 'MM/DD/RRRR'), 2108129597, 'valentine_gillian@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (40, 'Kati', 'Rulapaugh', to_date('11/16/1990', 'MM/DD/RRRR'), 7854637829, 'kati.rulapaugh@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (41, 'Youlanda', 'Schemmer', to_date('09/07/1966', 'MM/DD/RRRR'), 5415488197, 'youlanda@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (42, 'Dyan', 'Oldroyd', to_date('09/08/1995', 'MM/DD/RRRR'), 9134134604, 'doldroyd@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (43, 'Roxane', 'Campain', to_date('11/30/1998', 'MM/DD/RRRR'), 9072314722, 'roxane@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (44, 'Lavera', 'Perin', to_date('10/06/1980', 'MM/DD/RRRR'), 3056067291, 'lperin@perin.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (45, 'Erick', 'Ferencz', to_date('08/12/1979', 'MM/DD/RRRR'), 9077411044, 'erick.ferencz@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (46, 'Fatima', 'Saylors', to_date('12/23/1997', 'MM/DD/RRRR'), 9527682416, 'fsaylors@saylors.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (47, 'Jina', 'Briddick', to_date('06/05/1985', 'MM/DD/RRRR'), 6173995124, 'jina_briddick@briddick.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (48, 'Kanisha', 'Waycott', to_date('07/14/1987', 'MM/DD/RRRR'), 3234532780, 'kanisha_waycott@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (49, 'Emerson', 'Bowley', to_date('05/16/1990', 'MM/DD/RRRR'), 6083367444, 'emerson.bowley@bowley.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (50, 'Blair', 'Malet', to_date('09/04/1997', 'MM/DD/RRRR'), 2159079111, 'bmalet@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (51, 'Brock', 'Bolognia', to_date('03/03/1982', 'MM/DD/RRRR'), 2124029216, 'bbolognia@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (52, 'Lorrie', 'Nestle', to_date('04/15/1999', 'MM/DD/RRRR'), 9318756644, 'lnestle@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (53, 'Sabra', 'Uyetake', to_date('10/11/1973', 'MM/DD/RRRR'), 8039255213, 'sabra@uyetake.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (54, 'Marjory', 'Mastella', to_date('09/30/1969', 'MM/DD/RRRR'), 6108145533, 'mmastella@mastella.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (55, 'Karl', 'Klonowski', to_date('05/24/1979', 'MM/DD/RRRR'), 9088776135, 'karl_klonowski@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (56, 'Tonette', 'Wenner', to_date('01/24/1994', 'MM/DD/RRRR'), 5169686051, 'twenner@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (57, 'Amber', 'Monarrez', to_date('06/03/1980', 'MM/DD/RRRR'), 2159348655, 'amber_monarrez@monarrez.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (58, 'Shenika', 'Seewald', to_date('12/31/1965', 'MM/DD/RRRR'), 8184234007, 'shenika@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (59, 'Delmy', 'Ahle', to_date('05/03/1972', 'MM/DD/RRRR'), 4014582547, 'delmy.ahle@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (60, 'Deeanna', 'Juhas', to_date('04/14/1998', 'MM/DD/RRRR'), 2152119589, 'deeanna_juhas@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (61, 'Blondell', 'Pugh', to_date('08/26/1965', 'MM/DD/RRRR'), 4019608259, 'bpugh@aol.com', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (62, 'Jamal', 'Vanausdal', to_date('12/20/1990', 'MM/DD/RRRR'), 7322341546, 'jamal@vanausdal.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (63, 'Cecily', 'Hollack', to_date('03/25/1994', 'MM/DD/RRRR'), 5124863817, 'cecily@hollack.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (64, 'Carmelina', 'Lindall', to_date('11/17/1992', 'MM/DD/RRRR'), 3037247371, 'carmelina_lindall@lindall.com', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (65, 'Maurine', 'Yglesias', to_date('09/12/1966', 'MM/DD/RRRR'), 4147481374, 'maurine_yglesias@yglesias.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (66, 'Tawna', 'Buvens', to_date('05/14/1988', 'MM/DD/RRRR'), 2126749610, 'tawna@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (67, 'Penney', 'Weight', to_date('10/03/1976', 'MM/DD/RRRR'), 9077979628, 'penney_weight@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (68, 'Elly', 'Morocco', to_date('03/01/1978', 'MM/DD/RRRR'), 8143935571, 'elly_morocco@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (69, 'Ilene', 'Eroman', to_date('07/30/1966', 'MM/DD/RRRR'), 4109149018, 'ilene.eroman@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (70, 'Vallie', 'Mondella', to_date('04/27/2000', 'MM/DD/RRRR'), 2088625339, 'vmondella@mondella.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (71, 'Kallie', 'Blackwood', to_date('02/20/1981', 'MM/DD/RRRR'), 4153152761, 'kallie.blackwood@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (72, 'Johnetta', 'Abdallah', to_date('11/18/1989', 'MM/DD/RRRR'), 9192259345, 'johnetta_abdallah@aol.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (73, 'Bobbye', 'Rhym', to_date('02/24/1981', 'MM/DD/RRRR'), 6505285783, 'brhym@rhym.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (74, 'Micaela', 'Rhymes', to_date('12/06/1968', 'MM/DD/RRRR'), 9256473298, 'micaela_rhymes@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (75, 'Tamar', 'Hoogland', to_date('10/01/1970', 'MM/DD/RRRR'), 7403438575, 'tamar@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (76, 'Moon', 'Parlato', to_date('11/13/1972', 'MM/DD/RRRR'), 5858668313, 'moon@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (77, 'Laurel', 'Reitler', to_date('02/13/1979', 'MM/DD/RRRR'), 4105204832, 'laurel_reitler@reitler.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (78, 'Delisa', 'Crupi', to_date('08/20/1996', 'MM/DD/RRRR'), 9733542040, 'delisa.crupi@crupi.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (79, 'Viva', 'Toelkes', to_date('01/20/1979', 'MM/DD/RRRR'), 7734465569, 'viva.toelkes@gmail.com', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (80, 'Elza', 'Lipke', to_date('07/20/1966', 'MM/DD/RRRR'), 9739273447, 'elza@yahoo.com', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (81, 'Devorah', 'Chickering', to_date('07/22/1978', 'MM/DD/RRRR'), 5059758559, 'devorah@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (82, 'Timothy', 'Mulqueen', to_date('07/29/1987', 'MM/DD/RRRR'), 7183326527, 'timothy_mulqueen@mulqueen.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (83, 'Arlette', 'Honeywell', to_date('01/20/1989', 'MM/DD/RRRR'), 9047754480, 'ahoneywell@honeywell.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (84, 'Dominque', 'Dickerson', to_date('05/04/1981', 'MM/DD/RRRR'), 5109933758, 'dominque.dickerson@dickerson.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (85, 'Lettie', 'Isenhower', to_date('02/26/1992', 'MM/DD/RRRR'), 2166577668, 'lettie_isenhower@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (86, 'Myra', 'Munns', to_date('12/26/2000', 'MM/DD/RRRR'), 8179147518, 'mmunns@cox.net', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (87, 'Stephaine', 'Barfield', to_date('06/03/1984', 'MM/DD/RRRR'), 3107747643, 'stephaine@barfield.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (88, 'Lai', 'Gato', to_date('04/09/1968', 'MM/DD/RRRR'), 8477287286, 'lai.gato@gato.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (89, 'Stephen', 'Emigh', to_date('08/02/1969', 'MM/DD/RRRR'), 3305375358, 'stephen_emigh@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (90, 'Tyra', 'Shields', to_date('09/01/1968', 'MM/DD/RRRR'), 2152551641, 'tshields@gmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (91, 'Tammara', 'Wardrip', to_date('01/17/1990', 'MM/DD/RRRR'), 6508031936, 'twardrip@cox.net', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (92, 'Cory', 'Gibes', to_date('09/13/1970', 'MM/DD/RRRR'), 6265721096, 'cory.gibes@gmail.com', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (93, 'Danica', 'Bruschke', to_date('05/03/1989', 'MM/DD/RRRR'), 2547828569, 'danica_bruschke@gmail.com', '0');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (94, 'Wilda', 'Giguere', to_date('06/05/1980', 'MM/DD/RRRR'), 9078705536, 'wilda@cox.net', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (95, 'Elvera', 'Benimadho', to_date('07/22/1973', 'MM/DD/RRRR'), 4087038505, 'elvera.benimadho@cox.net', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (96, 'Carma', 'Vanheusen', to_date('02/03/1997', 'MM/DD/RRRR'), 5105037169, 'carma@cox.net', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (97, 'Malinda', 'Hochard', to_date('01/26/1975', 'MM/DD/RRRR'), 3177225066, 'malinda.hochard@yahoo.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (98, 'Natalie', 'Fern', to_date('08/11/1999', 'MM/DD/RRRR'), 3077048713, 'natalie.fern@hotmail.com', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (99, 'Lisha', 'Centini', to_date('05/21/1976', 'MM/DD/RRRR'), 7032353937, 'lisha@centini.org', '1');

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL, STATUS) 
VALUES (100, NULL, NULL, to_date('03/10/1998', 'MM/DD/RRRR'), 5047105840, 'arlene_klusman@gmail.com', '0');

commit;

SELECT * FROM customer;


