declare 
v_cnt number;
begin
    select count(*) into v_cnt from user_tables where table_name = upper('customer_address');
    if v_cnt = 0 then
        execute immediate('
            create table customer_address (
            address_id number,
            primary key(address_id),
            customer_id number,
            address_type varchar2(20),
            address_line1 varchar(50),
            address_line2 varchar(50),
            city  varchar(20),
            state  varchar(20),
            zip char(5))');
        dbms_output.put_line('customer_address table created');
        
    else
        dbms_output.put_line('customer_address table already exists');
    end if;
end;
/

SET DEFINE OFF
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (1, 1, 'Home', '4 Jersey Street', 'Lane 3 Apt 5', 'Boston', 'MA', '02215');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (2, 2, 'Home', '38938 Park Blvd', 'Null', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (3, 3, 'Office', '3 Aspen St', 'N/A', 'Worcester', 'MA', '01602');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (4, 4, 'Home', '19 Forest Street', 'Apt 4', 'Boston', 'MA', '02119');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (5, 5, 'Home', ' 43 West Walnut Park', 'Bancroft Street', 'Boston', 'MA', '02119');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (6, 6, 'Home', ' 835 South Street', 'Apt 12', 'Boston', 'MA', '02131');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (7, 7, 'Office', '74 St Mary Street', 'N/A', 'Boston', 'MA', '02215');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (8, 8, 'Home', 'Capen Street', 'Apt 5', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (9, 9, 'Home', '12 Wilmington Avenue', 'N/A', 'Boston', 'MA', '02124');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (10, 10, 'Home', '166 Everett Street', 'N/A', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (11, 11, 'Office', '28 Chelsea Street', '5th Floor Apt 11 ', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (12, 12, 'Home', '462 Geneva Avenue', 'Apt 7', 'Boston', 'MA', '02122');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (13, 13, 'Office', '4420 Washington Street', 'Denton Terrace', 'Boston', 'MA', '02131');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (14, 14, 'Office', '4 Copley Pl ', '7th Floor', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (15, 15, 'Home', '885 Huntington Ave', 'Apt 7', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (16, 16, 'Office', '72 Mannix Dr', 'Floor 1', 'Boston', 'MA', '02114');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (17, 17, 'Home', '7 Copley Pl', '3th Floor ', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (18, 18, 'Home', '559 Dorchester Avenue', 'Opposite to 7 Ellery Street', 'Boston', 'MA', '02127');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (19, 19, 'Home', '4 Jersey Street', 'N/A', 'Boston', 'MA', '02215');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (20, 20, 'Home', '28 Chelsea Street', '5th Floor Apt 11 ', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (21, 21, 'Home', '38938 Park Blvd', '2nd Floor', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (22, 22, 'Home', '255 Condor Street', 'Glendon Apt 6', 'Boston', 'MA', '02125');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (23, 23, 'Home', '875 Huntington Ave', 'Apt 8', 'Boston', 'MA', '02115');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (24, 24, 'Office', '255 Condor Street', 'Glendon 6th Floor', 'Boston', 'MA', '02125');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (25, 25, 'Home', '5 Mission Hill', '4 Lane Apt 7', 'Boston', 'MA', '02120');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (26, 26, 'Home', 'Mission Park', '14th Floor 142', 'Boston', 'MA', '02115');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (27, 27, 'Home', '94 North Hampton', 'Apt 1', 'Boston', 'MA', '02118');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (28, 28, 'Home', '38938 Park Blvd', '2nd Floor', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (29, 29, 'Home', '2 Newcastle st', 'N/A', 'Boston', 'MA', '02136');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (30, 30, 'Office', '48 High St', '4th Floor', 'Boston', 'MA', '02112');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (31, 31, 'Home', '38938 Park Blvd', 'Apt 9', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (32, 32, 'Home', 'Longwood Apartment', 'Floor 13', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (33, 33, 'Home', 'Jvue Apartment', 'Floor 4 Apt 43', 'Boston', 'MA', '02120');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (34, 34, 'Home', '883 Huntington Ave', 'Apt 5', 'Boston', 'MA', '02112');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (35, 35, 'Home', '3 Aspen St', 'Apt 7', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (36, 36, 'Home', '32860 Sierra Rd', 'Harvard Square', 'Boston', 'MA', '02147');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (37, 37, 'Home', '555 Main St', 'Apt 9', 'Boston', 'MA', '02103');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (38, 38, 'Home', '2 Se 3rd Ave', '4 Lane Apt 7', 'Boston', 'MA', '02117');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (39, 39, 'Home', '2239 Shawnee Mission Pky', 'Apt 15', 'Boston', 'MA', '02134');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (40, 40, 'Office', '2726 Charcot Ave', 'Apt 8', 'Boston', 'MA', '02115');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (41, 41, 'Home', '54169 N Main St', 'Fenway Street', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (42, 42, 'Home', '92 Main St', 'Floor 6', 'Boston', 'MA', '02127');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (43, 43, 'Home', '72 Mannix Dr', 'Floor 1', 'Boston', 'MA', '02114');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (44, 44, 'Home', '7 Copley Pl', '7th Floor', 'Boston', 'MA', '02154');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (45, 45, 'Office', '883 Huntington Ave', 'Apt 9', 'Boston', 'MA', '02101');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (46, 46, 'Office', '94 North Hampton', 'Apt 10', 'Boston', 'MA', '02118');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (47, 47, 'Home', '322 New Horizon Blvd', 'Muesum of Science', 'Boston', 'MA', '02102');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (48, 48, 'Home', '1 State Route 27', 'Charles ', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (49, 49, 'Home', '394 Manchester Blvd', 'Floor 6', 'Boston', 'MA', '02132');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (50, 50, 'Home', '6 S 33rd St', 'Mission Main', 'Boston', 'MA', '02104');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (51, 51, 'Home', '6 Greenleaf Ave', '6 Lane', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (52, 52, 'Home', '618 W Yakima Ave', '4 Lane Apt 7', 'Boston', 'MA', '02145');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (53, 53, 'Home', '74 S Westgate St', 'Bancroft Street', 'Boston', 'MA', '02136');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (54, 54, 'Home', '3273 State St', 'Apt 12', 'Boston', 'MA', '02138');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (55, 55, 'Home', '1 Central Ave', 'N/A', 'Boston', 'MA', '02144');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (56, 56, 'Office', '86 Nw 66th St #8673', 'Apt 5', 'Boston', 'MA', '02110');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (57, 57, 'Home', '2 Cedar Ave #84', '7th Floor Apt 15', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (58, 58, 'Home', '90991 Thorburn Ave', 'Opposite St', 'Boston', 'MA', '02102');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (59, 59, 'Office', '386 9th Ave N', 'Floor 8', 'Boston', 'MA', '02125');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (60, 60, 'Home', '74874 Atlantic Ave', 'Lane 6', 'Boston', 'MA', '02136');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (61, 61, 'Home', '366 South Dr', '4 Lane Apt 7', 'Boston', 'MA', '02163');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (62, 62, 'Home', '45 E Liberty St', 'Apt 1', 'Boston', 'MA', '02150');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (63, 63, 'Home', '6649 N Blue Gum St', '2nd Floor', 'Boston', 'MA', '02119');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (64, 64, 'Home', '4 B Blue Ridge Blvd', 'N/A', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (65, 65, 'Home', '8 W Cerritos Ave #54', 'Floor 9', 'Boston', 'MA', '02145');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (66, 66, 'Home', '639 Main St', 'Apt 9', 'Boston', 'MA', '02113');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (67, 67, 'Office', '34 Center St', 'Floor 13', 'Boston', 'MA', '02106');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (68, 68, 'Home', '3 Mcauley Dr', 'Floor 4 Apt 43', 'Boston', 'MA', '02109');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (69, 69, 'Home', '7 Eads St', 'Apt 5', 'Boston', 'MA', '02125');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (70, 70, 'Home', '7 W Jackson Blvd', 'Lane 2', 'Boston', 'MA', '02127');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (71, 71, 'Home', '5 Boston Ave #88', 'N/A', 'Boston', 'MA', '02123');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (72, 72, 'Home', '228 Runamuck Pl #2808', 'Cedar Grove Street', 'Boston', 'MA', '02117');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (73, 73, 'Home', '2371 Jerrold Ave', 'Apt 6', 'Boston', 'MA', '02130');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (74, 74, 'Office', '37275 St  Rt 17m M', 'Bancroft Street', 'Boston', 'MA', '02142');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (75, 75, 'Office', '25 E 75th St #69', 'Harvard Square', 'Boston', 'MA', '02134');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (76, 76, 'Office', '98 Connecticut Ave Nw', 'Fenway Street', 'Boston', 'MA', '02139');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (77, 77, 'Home', '56 E Morehead St', 'Bancroft Street', 'Boston', 'MA', '02140');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (78, 78, 'Home', '73 State Road 434 E', 'Apt 15', 'Boston', 'MA', '02117');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (79, 79, 'Home', '69734 E Carrillo St', 'Lane 5', 'Boston', 'MA', '02112');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (80, 80, 'Office', '255 Condor Street', 'N/A', 'Boston', 'MA', '02215');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (81, 81, 'Home', '875 Huntington Ave', 'Floor 16', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (82, 82, 'Home', '255 Condor Street', '1st Lane', 'Boston', 'MA', '01602');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (83, 83, 'Office', '4 Copley Pl ', '7th Floor', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (84, 84, 'Home', 'Mission Park', 'Apt 7', 'Boston', 'MA', '02119');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (85, 85, 'Home', '94 North Hampton', '4 Lane Apt 7', 'Boston', 'MA', '02131');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (86, 86, 'Home', '38938 Park Blvd', 'Mission Hill', 'Boston', 'MA', '02215');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (87, 87, 'Home', '2 Newcastle st', 'Apt 10', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (88, 88, 'Home', 'Jvue Apartment', 'Floor 6', 'Boston', 'MA', '02124');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (89, 89, 'Office', '38938 Park Blvd', 'N/A', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (90, 90, 'Home', 'Longwood Apartment', '6th Floor Apt 65', 'Boston', 'MA', '02124');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (91, 91, 'Office', 'Jvue Apartment', 'N/A', 'Boston', 'MA', '02122');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (92, 92, 'Home', '883 Huntington Ave', '8th Lane', 'Boston', 'MA', '02131');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (93, 93, 'Home', ' 43 West Walnut Park', 'Floor 5 Apt 6', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (94, 94, 'Home', ' 835 South Street', 'Apt 12', 'Boston', 'MA', '02128');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (95, 95, 'Office', '74 St Mary Street', 'Floor 7', 'Boston', 'MA', '02116');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (96, 96, 'Office', '895 Huntington Ave', '2nd Street ', 'Boston', 'MA', '02115');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (97, 97, 'Home', '12 Wilmington Avenue', 'Apt 4', 'Boston', 'MA', '02138');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (98, 98, 'Office', '166 Everett Street', 'Lane 6', 'Boston', 'MA', '02134');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (99, 99, 'Office', '360 Huntington Ave', '8th Lane', 'Boston', 'MA', '02115');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (100, 100, 'Home', 'Jvue Apartment', 'Opposite to Longwood', 'Boston', 'MA', '02106');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (101, 11, 'Home', '23 Whitridge Street', 'Cedar Grove Street', 'Boston', 'MA', '02124');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (102, 16, 'Home', '93 North Hampton St', 'Apt 4', 'Boston', 'MA', '02118');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (103, 30, 'Home', 'Jvue Apartment', 'Floor 9', 'Boston', 'MA', '02120');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (104, 53, 'Office', '801 Bolyston St', 'Floor 5th ', 'Boston', 'MA', '02110');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (105, 71, 'Office', '155 Congress St', '2nd Floor', 'Boston', 'MA', '02110');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (106, 83, 'Home', '5 Mission Hill', 'Harvard Square', 'Boston', 'MA', '02119');
INSERT INTO CUSTOMER_ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP) 
VALUES (107, 96, 'Home', 'Capen Street', 'N/A', 'Boston', 'MA', '02130');

commit;

SELECT * FROM customer_address;


